### ISSUE TITLE
enhancement: show output on bash (again)

### ISSUE THREAD

**Issue by malenki** [cobra/josm-update-script#2]
You could change the penultimat line which calls josm into
aoss java -jar -Xmx$mem -Dsun.java2d.opengl=true $dir/josm-$latestrev.jar $@ 2>&1 | tee ~/.josm/josm.log &
o that logging _and_ bash output is possible. The latter is often helpful to see what Josm is doing or did without having to have a view at the log

**Comment by cobra** [comment]
done in SHA: b3daf5d3fa267969998fc2b8c7988b87a10c50c6
