### ISSUE TITLE
open referenced images via bash call

### ISSUE THREAD

**Issue by malenki** [cobra/josm-update-script#3]
It would be nice to be able not only to open logs from bash but also georeferenced images. Would save some time, clicks and mousemeters :)

At the moment the call
josm-script.sh blah.gpx pic/*jpg
results in a java.lang.RuntimeException and the gpx isn't opened. Don't know if this possible with the sccript or if the jsm hackers should work at that, too

**Comment by cobra** [comment]
This is working fine for me since josm supports loading images, see http://josm.openstreetmap.de/ticket/4288

I couldn't reproduce this so far. This is definitely weird.

**Comment by cobra** [comment]
didn't occur anymore, closing.
